sonar.projectKey=payment-gateway-product-web
sonar.projectName=Payment Gateway Product Web
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/*.spec.ts,**/*.spec.tsx,src/test/**,src/assets/**,src/vite-env.d.ts

sonar.coverage.exclusions=**/*.spec.ts,**/*.spec.tsx,**/*.module.ts,src/main.ts,src/**/*.dto.ts,src/**/*.repository.ts,src/**/*.port.ts,src/application/ports/**,prisma/**,src/main.tsx,src/app/store.ts,src/config.ts,src/test/**,src/assets/**,src/vite-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/lcov.info

sonar.sourceEncoding=UTF-8
